---

- name: Install Nagios Plugins
  apt: name={{ item }} state=present
  with_items:
    - nagios-plugins
    - nagios-plugins-contrib
    - bc

- name: Install dns checks
  monitoring:
    state: present
    advisory: true
    check:
      name: check_dns
      serviceId: check_dns
      script: "/usr/lib/nagios/plugins/check_dns -s localhost -H {{ ansible_fqdn }} -w {{ monitor_dns_warn_timeout }} -c {{ monitor_dns_crit_timeout }}"
