---

- hosts: all
  roles:
      - { role: consul, tags: ['consul'] }
      - { role: baseline_monitoring, tags: ['checks'] }

- hosts: lldns
  roles:
      - { role: monitor_dns, tags: ['check_dns'] }

