---

- hosts: all
  roles:
      - { role: consul, tags: ['consul'] }
      - { role: baseline_monitoring, tags: ['checks'] }

- hosts: lldns
  roles:
      - { role: ansible-role-bind, tags: ['dns'] }
      - { role: monitor_dns, tags: ['check_dns'] }

- hosts: ipam
  roles:
      - { role: ipam, tags: ['ipam'] }
