# ansible-galaxy roles
# ansible-galaxy install -r requirements.yml -p shared-roles --force

# Use version 1.5.0 because it has Joe's forwarding feature
- src: https://github.com/resmo/ansible-role-bind
  version: "v1.5.0"
  name: ansible-role-bind

# NOTE: the latest ipam role will be moved to:
# ansible/roles/ipam
- src: git://git.locationlabs.com/ig/deploy/ipam
  version: origin/develop
  scm: git

- src: git://git.locationlabs.com/ansible/roles/consul
  version: "1.5.3"
  scm: git
  name: consul

- src: git://git.locationlabs.com/ansible/docker-roles/toolkit
  version: "1.26"
  scm: git
  name: docker-toolkit

- src: git://git.locationlabs.com/ig/roles/baseline_monitoring
  version: "1.1"
  scm: git
  name: baseline_monitoring
