# ansible-galaxy roles
# ansible-galaxy install -r requirements.yml -p shared-roles --force

- src: git://git.locationlabs.com/forks/github/resmo/ansible-role-bind
  version: origin/master
  scm: git
  name: ansible-role-bind

- src: git://git.locationlabs.com/ansible/roles/consul
  version: "1.5.3"
  scm: git
  name: consul

- src: git://git.locationlabs.com/ansible/docker-roles/toolkit
  version: "1.26"
  scm: git
  name: docker-toolkit

- src: git://git.locationlabs.com/ig/roles/baseline_monitoring
  version: "1.1"
  scm: git
  name: baseline_monitoring
